# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_num_gpus": "00_utils.gpu.ipynb",
         "set_gpu_memory_limit": "00_utils.gpu.ipynb",
         "set_gpu_list_memory_limit": "00_utils.gpu.ipynb",
         "recursive_get_size": "00_utils.misc.ipynb",
         "log_init": "00_utils.misc.ipynb",
         "log_critical": "00_utils.misc.ipynb",
         "log_error": "00_utils.misc.ipynb",
         "log_warning": "00_utils.misc.ipynb",
         "log_info": "00_utils.misc.ipynb",
         "log_debug": "00_utils.misc.ipynb",
         "verify_audioengine_dataset": "00_utils.schema.ipynb",
         "audioengine_dataset_schema": "00_utils.schema.ipynb",
         "read_tsv": "utils.imports.common_voice.ipynb",
         "delete_pandas_columns": "utils.imports.common_voice.ipynb"}

modules = ["utils/gpu.py",
           "utils/misc.py",
           "utils/schema.py",
           "audio_classification.py",
           "utils/imports/common_voice.py"]

doc_url = "https://LizardLad.github.io/audioengine/"

git_url = "https://github.com/LizardLad/audioengine/tree/master/"

def custom_doc_links(name): return None
