# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/utils.imports.common_voice.ipynb (unless otherwise specified).

__all__ = ['read_tsv', 'delete_pandas_columns']

# Cell

import pandas as pd
import tensorflow as tf
import tensorflow_io as tfio

from typing import TextIO

import audioengine
from ..schema import verify_audioengine_dataset

# Cell

def read_tsv(tsv_filepointer: TextIO):
    """The input filepointer should already be open with no lines read"""
    tsv_data_df = pd.read_csv(tsv_filepointer, sep = '\t')
    return tsv_data_df

# Cell

def delete_pandas_columns(df: pd.DataFrame, column_list: list):
    for column in column_list:
        del df[column]
    return df