# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_utils.wav_utils.ipynb (unless otherwise specified).

__all__ = ['libwavutils_rel_path', 'libwavutils_abs_path', 'libwavutils', 'get_max_samples_in_wav_from_directory']

# Cell

import ctypes
import os

libwavutils_rel_path = 'audioengine/clib/libwavutil.so'
libwavutils_abs_path =os.path.abspath(libwavutils_rel_path)
libwavutils = ctypes.CDLL(libwavutils_abs_path)

# Cell

def get_max_samples_in_wav_from_directory(directory: str) -> int:
    directory_c_str = ctypes.c_char_p(directory.encode())
    max_samples = libwavutils.get_max_samples_in_wav_from_directory(directory_c_str)
    return max_samples